/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Softphone/Avatar.vue')['default']
    Clock: typeof import('./src/components/Softphone/Notification/Clock.vue')['default']
    Control: typeof import('./src/components/Softphone/Control.vue')['default']
    Dialpad: typeof import('./src/components/Softphone/Dialpad.vue')['default']
    Hold: typeof import('./src/components/Softphone/Notification/Hold.vue')['default']
    Incoming: typeof import('./src/components/Softphone/Notification/Incoming.vue')['default']
    Item: typeof import('./src/components/Softphone/Search/Item.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Softphone/Search.vue')['default']
    Softphone: typeof import('./src/components/Softphone.vue')['default']
    User: typeof import('./src/components/Softphone/User.vue')['default']
  }
}
